### ISSUE TITLE
Run instructions

### ISSUE THREAD

**Issue by CarlosLopezES** [rekyuu/telegram_instagram_preview_bot#1]
Hi,

I tried to deploy it on my server with the docker compose but it's not working, also I've tried to deploy manually with Python, and it's not working also.

Can you post some clue to run it? Thanks a lot!

**Comment by rekyuu** [comment]
Hey, sorry for the disappointment, but I never got this to work myself. I just pushed the code I had here unfortunately. If you get it to work somehow I'd love to see it though!
